### PR TITLE
pmm: remove `Mutex` around direct map address

### PR DESCRIPTION
**Pull request by 00xc**
The direct mapping address is never modified once set, so remove the lock around it, reducing overhead.

### CODE REVIEW

**Comment by mdpatelcsecon** [comment]
This Mutex is being used as an admittedly poor way to guard access to the direct mapping region as a whole. It's going to eventually get rewritten using a safer interface to access the direct map instead.

**Comment by mdpcs3544** [comment]
This Mutex is being used as an admittedly poor way to guard access to the direct mapping region as a whole. It's going to eventually get rewritten using a safer interface to access the direct map instead.

**Comment by mdpcs3544** [comment]
This issue should be addressed by #76

**Comment by 00xc** [comment]
> This Mutex is being used as an admittedly poor way to guard access to the direct mapping region as a whole. It's going to eventually get rewritten using a safer interface to access the direct map instead.

As far as I understand, currently the lock guard is dropped as soon as the arithmetic expression completes, meaning the resulting pointer would be written to without locking.

**Comment by mdpcs3544** [comment]
Yes that's true. This 'solution' was a really poor one and I'm going to work on a much better one that provides safer access to the direct map.

Also I just wanted to say I really appreciate your contributions to this project thus far.

**Comment by mdpcs3544** [comment]
It looks like no matter how we we access the direct map region it is always unsafe because the memory we're accessing could also be mapped elsewhere. Thus it is impossible to implement a completely safe interface over it. 

As such I'm reopening and merging this PR.

**Pull request merged**
