### PR TITLE
Add FADT (Fixed ACPI Description Table) definition and implementation, this adds a partial implementation of the FADT

### PR DESCRIPTION
**Pull request by xadaemon**

### CODE REVIEW

**Review by EthanPlant — APPROVED** [review]
LGTM

**Comment by mdpcs3544** [comment]
Is this PR ready to be merged? It looks like there are some rebase conflicts that need to be taken care of so whoever merges it might need to do so from the commandline.

**Comment by EthanPlant** [comment]
Yeah I was gonna leave it to @neonimp to fix the rebase conflicts if it's ready to merge since I know he had a little bit he still wanted to do on the FADT but if it's good to merge I can always fix it

**Comment by xadaemon** [comment]
> Yeah I was gonna leave it to @neonimp to fix the rebase conflicts if it's ready to merge since I know he had a little bit he still wanted to do on the FADT but if it's good to merge I can always fix it

I just fixed merge issue

**Review by EthanPlant — APPROVED** [review]

**Pull request merged**
